exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]

indent-width = 4
line-length = 120

target-version = "py311"

[lint]
ignore = [
  "ANN",
  "COM812",
  "D",
  "E741",
  "ERA001",
  "FBT002",
  "FBT003",
  "FIX002",
  "G004",
  "ISC001",
  "PLR0913",
  "PT009",
  "PTH100",
  "PTH103",
  "PTH104",
  "PTH107",
  "PTH109",
  "PTH110",
  "PTH113",
  "PTH118",
  "PTH119",
  "PTH120",
  "PTH122",
  "PTH123",
  "RUF001",
  "RUF002",
  "RUF003",
  "RUF100",
  "T201",
  "TD002",
  "TD003",
]
select = ["ALL"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
indent-style = "space"
quote-style = "double"

skip-magic-trailing-comma = false # list等の最後の要素の後のコンマを削除しない。

line-ending = "lf" # "auto" | "lf" | "cr-lf" | "native"
