name: Weekly Docker Image Build

on:
  schedule:
    # 毎週月曜日の午前0時（UTC）にトリガー
    - cron: '0 0 * * 1'
  workflow_dispatch: # 手動実行も可能

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ci-base
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: docker-${{ steps.meta.outputs.version }}
          name: Weekly Docker Image ${{ steps.meta.outputs.version }}
          body: |
            ## Automated Weekly Docker Image Build

            - Built on: ${{ github.event.repository.updated_at }}
            - Build timestamp: ${{ steps.meta.outputs.created }}

            ### Image Details
            - Repository: ${{ github.repository }}
            - Image tag: ${{ steps.meta.outputs.version }}