name: Integration Tests

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-base:latest
      # options: --user appuser:appuser
    environment: dev
    steps:
      - uses: Kesin11/actions-timeline@v2
        with:
          show-waiting-runner: true

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -e .

      - name: Run integration test(test_api_keys)
        run: |
          pytest tests/integration_tests/test_api_keys.py
        env:
          API_MODELS: ${{ secrets.API_MODELS }}
          ANTHROPIC_API_KEYS: ${{ secrets.ANTHROPIC_API_KEYS }}
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
          GROQ_API_KEYS: ${{ secrets.GROQ_API_KEYS }}
          MISTRAL_API_KEYS: ${{ secrets.MISTRAL_API_KEYS }}
          MODEL_NAME_DEFAULT: ${{ secrets.MODEL_NAME_DEFAULT }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: "pk-lf-e84a69c3-f0c7-49f2-be2a-77109e546a1a"
          LANGFUSE_HOST: "https://us.cloud.langfuse.com"

      - name: Run integration test(test_performance_first_run)
        run: |
          pytest tests/integration_tests/test_performance_first_run.py
        env:
          API_MODELS: ${{ secrets.API_MODELS }}
          ANTHROPIC_API_KEYS: ${{ secrets.ANTHROPIC_API_KEYS }}
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
          GROQ_API_KEYS: ${{ secrets.GROQ_API_KEYS }}
          MISTRAL_API_KEYS: ${{ secrets.MISTRAL_API_KEYS }}
          MODEL_NAME_DEFAULT: ${{ secrets.MODEL_NAME_DEFAULT }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: "pk-lf-e84a69c3-f0c7-49f2-be2a-77109e546a1a"
          LANGFUSE_HOST: "https://us.cloud.langfuse.com"

      - name: Run integration test(test_performance_second_run)
        run: |
          pytest tests/integration_tests/test_performance_second_run.py
        env:
          API_MODELS: ${{ secrets.API_MODELS }}
          ANTHROPIC_API_KEYS: ${{ secrets.ANTHROPIC_API_KEYS }}
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
          GROQ_API_KEYS: ${{ secrets.GROQ_API_KEYS }}
          MISTRAL_API_KEYS: ${{ secrets.MISTRAL_API_KEYS }}
          MODEL_NAME_DEFAULT: ${{ secrets.MODEL_NAME_DEFAULT }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: "pk-lf-e84a69c3-f0c7-49f2-be2a-77109e546a1a"
          LANGFUSE_HOST: "https://us.cloud.langfuse.com"

      - name: Run integration test(test_data_quality_evaluation)
        run: |
          pytest tests/integration_tests/test_data_quality_evaluation.py
        env:
          API_MODELS: ${{ secrets.API_MODELS }}
          ANTHROPIC_API_KEYS: ${{ secrets.ANTHROPIC_API_KEYS }}
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
          GROQ_API_KEYS: ${{ secrets.GROQ_API_KEYS }}
          MISTRAL_API_KEYS: ${{ secrets.MISTRAL_API_KEYS }}
          MODEL_NAME_DEFAULT: ${{ secrets.MODEL_NAME_DEFAULT }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: "pk-lf-e84a69c3-f0c7-49f2-be2a-77109e546a1a"
          LANGFUSE_HOST: "https://us.cloud.langfuse.com"

      - name: Get run times script
        run: |
          python ./scripts/python/get_run_times.py
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create job summary
        run: |
          echo "## Integration Tests Duration Chart" >> $GITHUB_STEP_SUMMARY
          echo "This chart shows the duration of integration tests over time:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat chart.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Last updated: $(date)" >> $GITHUB_STEP_SUMMARY

      - name: Upload chart
        uses: actions/upload-artifact@v4
        with:
          name: chart
          path: chart.md
