name: Integration Tests

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: Kesin11/actions-timeline@v2
        with:
          show-waiting-runner: true

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false # グローバル環境でインストール
      - name: Install dependencies
        run: poetry install --with test,lint

      - name: Run integration test(test_performance_first_run)
        run: |
          pytest tests/integration_tests/test_performance_first_run.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Run integration test(test_performance_second_run)
        run: |
          pytest tests/integration_tests/test_performance_second_run.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Run integration test(test_data_quality_evaluation)
        run: |
          pytest tests/integration_tests/test_data_quality_evaluation.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Get run times script
        run: |
          python ./scripts/python/get_run_times.py
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create job summary
        run: |
          echo "## Integration Tests Duration Chart" >> $GITHUB_STEP_SUMMARY
          echo "This chart shows the duration of integration tests over time:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat chart.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Last updated: $(date)" >> $GITHUB_STEP_SUMMARY

      - name: Upload chart
        uses: actions/upload-artifact@v4
        with:
          name: chart
          path: chart.md
